Basic interfaces
FI-61m-distributed-systems/users_db_api pull request #1
Opened 2017-05-07 12:49 UTC by polyvika

2017-05-07 13:49 UTC, semensan requested changes
add moMey interfaSe ->add money transfer interface
athorization -> aUthorization

2017-05-07 13:49 UTC, semensan commented on authorization.py
> +                    print "Welcome ",log
что за *?
куда print? какой print?
и зачем вообще вынимать толькочто запихнутое значение?
и даже если, а вдруг БД распределённая, не сработает условие
итак
1) твоя программка будет висеть на серваке, если кто и увидит print, это будут сетевые инженеры. Писать лог - ок, но в формате лога, "<user> logged in", "recieved wrong data: <...>", ...
2) а если б проверить надо было 50 полей? табуляция б до луны достала
if !1
 err 1;
else if !2
 err 2;
else ...
else
 ok;
наверно лучше
3) вытягивать с сервера только что запихнутые данные - плохо

2017-05-07 13:49 UTC, semensan commented on authorization.py
> +            connect.close()
я думаю классы на то и классы чтобы убирать за собой
на сколько я знаю close вызывается автоматом при удалении connection

2017-05-07 13:49 UTC, semensan commented on money.py
> +
я уже успел заметить манию пустых строк, но в команде БД пожалуй лишняя пустая строчка

2017-05-10 12:54 UTC, semensan approved these changes

2017-05-10 13:28 UTC, semensan requested changes
форматировка - ужас
надеялся что поймёшь и переделаешь с прошлого раза
уважай пожалуйста людей
придерживайся одного coding style
такой кодинг не приветствуется нигде
если так лень самой, разберись в своём IDE, пусть он за тебя форматирует
1) отделяй импорты и функции пустой строкой
одной строкой
2) не делай лишних пропусков
я понимаю если там он прям просится, но у тебя они везде
даже в запросах
3) раздели определения функций от их использования
4) вставь таки заглушки
5) когда пишешь код, прошу, помни что его кому-то придётся читать

2017-05-10 13:28 UTC, semensan commented on authorization.py
> +from get_parametra import config
отделяй библиотеки от всего и функции друг от друга пустой строчкой
во всех файлах

2017-05-10 13:28 UTC, semensan commented on authorization.py
> +def customer(log,p, email):
customer - сущность а не функция
функция то что делает? переименуй

2017-05-10 13:28 UTC, semensan commented on authorization.py
> +            connect.close()
либо недочинила либо не понимаешь как работают объекты и исключения

2017-05-10 13:28 UTC, semensan commented on authorization.py
> +customer(get_login(),get_password(),get_email())
сделай определения отдельным модулем
вызывать будешь в другом месте
пока создай папку test и там тестируй

2017-05-10 13:28 UTC, semensan commented on config.py
> +from get_parametra import config
имя модуля не говорит ни о чём, переименуй

2017-05-10 13:28 UTC, semensan commented on config.py
> +        CREATE TABLE account
ты при каждом connect будешь таблицу создавать?
либо переделай логику либо переименуй функцию

2017-05-10 13:28 UTC, semensan commented on config.py
> +            conn.close()
видимо таки второй случай
ты это нашла где-то?

2017-05-10 13:28 UTC, semensan commented on connect.ini
> +port = 5433
пустую строку в конец файла

2017-05-10 13:28 UTC, semensan commented on create.sql
> +CREATE DATABASE "Game_Webmoney"
не догоняю чего эта команда в  отдельном файле

2017-05-10 13:28 UTC, semensan commented on get_parametra.py
> +    # create a parser
читать tutorials это ок, но оставлять тупые комменты смысла особо нет
комментарии нужны там где не очевиден смысл кода

2017-05-10 13:28 UTC, semensan commented on money.py
> +def get_login():
а вот и явный признак ещё до моего коммента выделить эти функции в отдельный модуль

2017-05-10 13:28 UTC, semensan commented on money.py
> +def money_in_pocket(loginFROM, moneyFROM,loginTO, moneyTO):
по названию - узнать сколько денег
по агрументам - пересылка денег
уважай тех кто будет пользоваться твоим кодом

2017-05-10 13:28 UTC, semensan commented on money.py
> +    if moneyFROM == moneyTO:
ну и нафига их вообще 2?

2017-05-10 13:28 UTC, semensan commented on money.py
> +            cursor = connect.cursor()
кажеться эти 3 строчки уже где-то были...
дублирование кода - почти всегда плохо
у начинающиго прогера - всегда

2017-05-10 13:28 UTC, semensan commented on money.py
> +                cursor.execute(
ну что за табы...

2017-05-10 13:28 UTC, semensan commented on authorization.py
> +            print "Welcome ",log
здесь должна быть заглушка

2017-05-10 13:28 UTC, semensan commented on money.py
> +            print(error)
допиши сюда 2 заглушки
одна будет отправлять "ок" другая ошибку

2017-05-10 13:28 UTC, semensan commented on authorization.py
> +        print(error)
и здесь заглушка

2017-05-10 13:28 UTC, semensan commented on registration.py
> +        print(error)
и тут 2 заглушки

2017-05-10 13:28 UTC, semensan commented on registration.py
> +def get_login():
и опять эти функции...

2017-05-10 13:36 UTC, semensan commented
да, ещё по сообщениям
add setting for db and script for getting config:
настройКИ (settingS)
и вообще посмотрел и не понял зачем тут файл настроек
все те параметры могут быть агрументами по умолчанию функции (функций)
Fix review and add config:
1) ты чинила сам review? или всё таки его issues?
2) так а прошлый коммит что, с конфигом работает а его самого там ещё нет?

после починки перепишешь историю (не забудь про баги прошлых сообщений)

2017-05-11 08:52 UTC, polyvika commented
По поводу запросу по созданию БД. Для Posgres в Python-е походу нельзя создавать, конекты возможны только к уже существующей БД. Видела создание БД только для sqlite. Если найдёшь, что можно создать с меня шоколадка))

2017-05-11 12:05 UTC, semensan commented
первая ссылка гугла
http://stackoverflow.com/questions/19426448/creating-a-postgresql-db-using-psycopg2
подключаешься к БД, создаваемой по умолчанию
ещё лучше сделать в скрипте аргумент, запрашивающий нужные данные, если они вдруг созданы не по умолчанию

2017-05-11 12:06 UTC, semensan commented
fix codding style: code -> coding

2017-05-11 12:19 UTC, semensan reviewed
с прошлых комментов не всё дочинила
дочини
разнеси определения и вызовы
warning и ok переделай во что-то вменяемое
это может быть даже 1 функция
send(status, message, data, ...)
может 2
sendError sendOk (message, data, ...)
может целое семейство
send*(data, ...)
(*-some response)

2017-05-11 12:19 UTC, semensan commented on authorization.py
> +        WARNING()
1) зачем капс? низачем
и вообще это скорее error
да и тот не простой а с отправкой сообщения
2) в таком виде на любую ошибку одно сообщение
для дебага плохо
допили аргументы

2017-05-11 12:19 UTC, semensan commented on authorization.py
> +            OK()
1) капс
2) что ок? функции должны иметь говорящие названия
эта целый запрос отправляет
либо названием говори что кому ок либо аргументами

2017-05-13 15:33 UTC, semensan commented on authorization.py
> +from connection import connection
... и вы будете вызывать connection пока подключаете connection

2017-05-13 17:03 UTC, polyvika commented on authorization.py
> +from connection import connection
http://www.postgresqltutorial.com/postgresql-python/connect/
посмотрев такие примеры, я поняла, что это норма))

2017-05-22 15:11 UTC, semensan requested changes
1. inter.txt вынеси в репозиторий documentation
ну или может я раньше обновлю, тогда с моими изменениями глянешь, поправишь
2. https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP
3. по транзакциям
разделим их на 2 типа
get и update
1й как сейчас
2й - последовательность из insert/update/delete

2017-05-22 15:11 UTC, semensan commented on call_func.py
> +from stub import send_err
заглушки на то и заглушки чтобы потом безболезненно их заменить
назови нормально

2017-05-22 15:11 UTC, semensan commented on call_func.py
> +def call_func(d):
прочитав название функции я прям осознал смысл жизни
я б ещё понял callback
лучше  process_packet / process / ...
и что за d? packet / request / ...

2017-05-22 15:11 UTC, semensan commented on call_func.py
> +    if data["request"]=="get":
python умеет switch/case по строкам?
если да лучше переделай под него

2017-05-22 15:11 UTC, semensan commented on call_func.py
> +        return set_data(data["transaction"][0]["user"], data["transaction"][0]["password"],
только первый? а остальные?

2017-05-22 15:11 UTC, semensan commented on client.py
> +print s
ну вот любите вы лишние переменные
чем не угодил print response.headers['Content']?

2017-05-22 15:11 UTC, semensan commented on client.py
> +response.close()
эээ
так точно надо?

2017-05-22 15:11 UTC, semensan commented on server.py
> +    BaseHTTPServer.HTTPServer(('localhost',8000), MyServer).serve_forever()
ip:port параметрами командной строки

2017-05-22 15:11 UTC, semensan commented on server.py
> +    def do_POST(s):
ну что за s?

2017-05-22 15:11 UTC, semensan commented on server.py
> +            s.send_header('Content',call_func(data))
так эта функция даже не пакет а только json обрабатывает
назови соответствующе

2017-05-22 15:11 UTC, semensan commented on server.py
> +            s.send_header('Content',404)
404 - код ответа сервера, значит "не найдено"
1. это НЕ содержание пакета
2. ты уже отправила 200 (всё ок)
3. у ошибки сервера другой код

2017-05-22 15:11 UTC, semensan commented on stub.py
>      h = hashlib.md5(password)
md5 у себя уже можешь убирать

2017-05-22 15:11 UTC, semensan commented on update.py
> +        if field=="money":
жуть
сделай через map

2017-05-24 15:37 UTC, polyvika commented
switch/case к сожалению нету.
+надо уточнить интефейсы. Ибо скорей всего придётся немного все обёртки переписать.

2017-05-25 15:31 UTC, semensan commented on update.py
> +        SET """+ field+"""=%s
мы же вроде договорились, непередавать это напрямую
сделай словарь (map)
пусть он себе хранит "money" -> "money", ...

2017-05-25 15:35 UTC, semensan commented on configure.py
> +      print 'test.py -s <host> -p <password> -l <port>'
почему test.py?
тут наверно argv[0]

2017-05-25 15:35 UTC, semensan commented on configure.py
> +         print 'tests.py -s <host> -p <password> -l <port>'
тут вообще tests

2017-05-25 15:37 UTC, semensan commented on configure.py
> +                LC_CTYPE = 'Russian_Russia.1251'
ой не нравится мне это 1251...
может таки utf-8?

2017-05-28 06:29 UTC, semensan approved these changes

2017-05-28 06:30 UTC, merged

2017-05-28 10:26 UTC, polyvika commented
Урааа мердж =-O